# Generated by Django 3.0.3 on 2020-02-15 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='did',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='thread',
            name='space',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='forum.Thread')),
            ],
        ),
    ]
